### ISSUE TITLE
Module 'Wdevs_Dymo' is not correctly registered.

### ISSUE THREAD

**Issue by ghost** [Paulsky/magento-2-dymo-labelwriter#2]
Hi, we tried to install this plugin on Magento 2.3.0.
During the installation everything seems fine, but something goes wrong when i try to enter in Stores > Configuration > Shipping Methods.
And magento log this error:

`1 exception(s):
Exception #0 (InvalidArgumentException): Module 'Wdevs_Dymo' is not correctly registered.

Exception #0 (InvalidArgumentException): Module 'Wdevs_Dymo' is not correctly registered.
#0 /var/www/magento2/vendor/magento/framework/Module/Dir/Reader.php(177): Magento\Framework\Module\Dir->getDir('Wdevs_Dymo', '')
#1 /var/www/magento2/vendor/magento/framework/Module/Dir/Reader.php(128): Magento\Framework\Module\Dir\Reader->getModuleDir('', 'Wdevs_Dymo')
#2 /var/www/magento2/vendor/magento/framework/Module/Dir/Reader.php(111): Magento\Framework\Module\Dir\Reader->getFiles('composer.json', '')
#3 /var/www/magento2/vendor/magento/framework/Module/Dir/Reader.php(96): Magento\Framework\Module\Dir\Reader->getFilesIterator('composer.json')
#4 /var/www/magento2/vendor/magento/framework/Module/PackageInfo.php(93): Magento\Framework\Module\Dir\Reader->getComposerJsonFiles()
#5 /var/www/magento2/vendor/magento/framework/Module/PackageInfo.php(285): Magento\Framework\Module\PackageInfo->load()
#6 /var/www/magento2/vendor/temando/module-shipping-m2/Block/Adminhtml/System/Config/Form/Field/Version.php(51): Magento\Framework\Module\PackageInfo->getVersion('Temando_Shippin...')
#7 /var/www/magento2/vendor/magento/module-config/Block/System/Config/Form/Field.php(77): Temando\Shipping\Block\Adminhtml\System\Config\Form\Field\Version->_getElementHtml(Object(Magento\Framework\Data\Form\Element\Note))
#8 /var/www/magento2/vendor/magento/module-config/Block/System/Config/Form/Field.php(51): Magento\Config\Block\System\Config\Form\Field->_renderValue(Object(Magento\Framework\Data\Form\Element\Note))
#9 /var/www/magento2/vendor/magento/framework/Data/Form/Element/AbstractElement.php(460): Magento\Config\Block\System\Config\Form\Field->render(Object(Magento\Framework\Data\Form\Element\Note))
#10 /var/www/magento2/vendor/magento/framework/Data/Form/Element/AbstractElement.php(474): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#11 /var/www/magento2/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(86): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#12 /var/www/magento2/vendor/magento/module-config/Block/System/Config/Form/Fieldset.php(66): Magento\Config\Block\System\Config\Form\Fieldset->_getChildrenElementsHtml(Object(Magento\Framework\Data\Form\Element\Fieldset))
#13 /var/www/magento2/vendor/magento/framework/Data/Form/Element/AbstractElement.php(460): Magento\Config\Block\System\Config\Form\Fieldset->render(Object(Magento\Framework\Data\Form\Element\Fieldset))
#14 /var/www/magento2/vendor/magento/framework/Data/Form/Element/AbstractElement.php(474): Magento\Framework\Data\Form\Element\AbstractElement->getHtml()
#15 /var/www/magento2/vendor/magento/framework/Data/Form.php(329): Magento\Framework\Data\Form\Element\AbstractElement->toHtml()
#16 /var/www/magento2/vendor/magento/framework/Data/Form.php(344): Magento\Framework\Data\Form->toHtml()
#17 /var/www/magento2/vendor/magento/module-backend/Block/Widget/Form.php(101): Magento\Framework\Data\Form->getHtml()
#18 /var/www/magento2/vendor/magento/module-backend/view/adminhtml/templates/widget/form.phtml(15): Magento\Backend\Block\Widget\Form->getFormHtml()
#19 /var/www/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/magent...')
#20 /var/www/magento2/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Form), '/var/www/magent...', Array)
#21 /var/www/magento2/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/magent...')
#22 /var/www/magento2/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#23 /var/www/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#24 /var/www/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#25 /var/www/magento2/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#26 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#27 /var/www/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(508): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#28 /var/www/magento2/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(28): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#29 /var/www/magento2/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/magent...')
#30 /var/www/magento2/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/magent...', Array)
#31 /var/www/magento2/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/magent...')
#32 /var/www/magento2/vendor/magento/module-backend/Block/Template.php(129): Magento\Framework\View\Element\Template->_toHtml()
#33 /var/www/magento2/vendor/magento/framework/View/Element/AbstractBlock.php(668): Magento\Backend\Block\Template->_toHtml()
#34 /var/www/magento2/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Element\AbstractBlock->toHtml()
#35 /var/www/magento2/vendor/magento/framework/View/Layout.php(533): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#36 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#37 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('system.config.e...', false)
#38 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('content', false)
#39 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('content')
#40 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('content', false)
#41 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...', false)
#42 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#43 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('admin.scope.col...', false)
#44 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('main.col', false)
#45 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#46 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('main.col', false)
#47 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.main.conta...', false)
#48 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#49 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.main.conta...', false)
#50 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.content', false)
#51 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#52 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.content', false)
#53 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#54 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#56 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('backend.page', false)
#57 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#58 /var/www/magento2/vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('backend.page', false)
#59 /var/www/magento2/vendor/magento/framework/View/Layout.php(535): Magento\Framework\View\Layout->_renderContainer('root', false)
#60 /var/www/magento2/vendor/magento/framework/View/Layout.php(488): Magento\Framework\View\Layout->renderNonCachedElement('root')
#61 /var/www/magento2/vendor/magento/framework/View/Layout.php(954): Magento\Framework\View\Layout->renderElement('root')
#62 /var/www/magento2/generated/code/Magento/Framework/View/Layout/Interceptor.php(37): Magento\Framework\View\Layout->getOutput()
#63 /var/www/magento2/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput()
#64 /var/www/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#65 /var/www/magento2/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(24): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#66 /var/www/magento2/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#67 /var/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#68 /var/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#69 {main}`

Any ideas on this error? :)

**Comment by Paulsky** [comment]
I'm sorry, I have no idea at this moment. I will try to replicate this issue in the couple of days. If you have any solution in the mean time, please share it with me.

**Comment by Paulsky** [comment]
I just tested the module in Magento 2.3.**1** (Manual installation). Everything seems fine and I don't receive any errors. Also no errors in the view Stores > Configuration > Shipping Methods.  Are you in production modus? Did you clear the caches and upgraded your installation described as in the 'read me' file in section 'Installation: 2. enable the module'?

**Comment by ghost** [comment]
Hello! yes, we have done all the steps. We use PHP version 7.2, is that the error?

**Comment by Paulsky** [comment]
I don't think that should matter. Are you in production modus? Maybe you could try to compile and deploy again with setup:di:compile and setup:static-content:deploy?

**Comment by Paulsky** [comment]
Did you find a solution for your problem? Please share it, so I can close this issue.
