### ISSUE TITLE
Doesn't print second line of street address

### ISSUE THREAD

**Issue by DGZ4life** [Paulsky/magento-2-dymo-labelwriter#4]
If there is a second line in the street address it doesn't print this.

**Comment by DGZ4life** [comment]
Solved! 

For others with same problem, change the code in addressformatter to:

function formatStreetLine(streetArray) {
        var street2 = streetArray;
		var street = street2.join(' ');
        street = capitalizeEachWord(street.trim());
        return street;
    }

**Comment by Paulsky** [comment]
Nice, thank you for your contribution! Sorry for my late reply. When I have time and resources again, I will investigate how I can add this.
